const currencies = [
  {value:'USD', label:'USD | US Dollar'},
  {value:'CAD', label:'CAD | Canadian Dollar'},
  {value:'EUR', label:'EUR | Euro'},
  {value:'ARS', label:'ARS | Argentine Peso'},
  {value:'AUD', label:'AUD | Australian Dollar'},
  {value:'BSD', label:'BSD | Bahamian Dollar'},
  {value:'BRL', label:'BRL | Brazilian Real'},
  {value:'CLP', label:'CLP | Chilean Peso'},
  {value:'CNY', label:'CNY | Chinese Yuan Renminbi'},
  {value:'COP', label:'COP | Colombian Peso'},
  {value:'CRC', label:'CRC | Costa Rican Col&oacute;n'},
  {value:'DOP', label:'DOP | Dominican Peso'},
  {value:'EGP', label:'EGP | Egyptian Pound'},
  {value:'HUF', label:'HUF | Hungarian Forint'},
  {value:'INR', label:'INR | Indian Rupee'},
  {value:'IDR', label:'IDR | Indonesian Rupiah'},
  {value:'ILS', label:'ILS | Israeli New Sheqel'},
  {value:'JMD', label:'JMD | Jamaican Dollar'},
  {value:'JPY', label:'JPY | Japanese Yen'},
  {value:'MXN', label:'MXN | Mexican Peso'},
  {value:'MAD', label:'MAD | Moroccan Dirham'},
  {value:'NZD', label:'NZD | New Zealand Dollars'},
  {value:'PLN', label:'PLN | Polish Zloty'},
  {value:'PKR', label:'PKR | Pakistani Rupee'},
  {value:'RON', label:'RON | Romanian Leu'},
  {value:'RUB', label:'RUB | Russian Ruble'},
  {value:'SAR', label:'SAR | Saudi Riyal'},
  {value:'CHF', label:'CHF | Swiss Franc'},
  {value:'THB', label:'THB | Thai Baht'},
  {value:'TTD', label:'TTD | Trinidad and Tobago Dollar'},
  {value:'TRY', label:'TRY | Turkish Lira'},
  {value:'UAH', label:'UAH | Ukrainian Hryvnia'},
  {value:'AED', label:'AED | United Arab Emirates Dirham'},
  {value:'VEB', label:'VEB | Venezuelan Bol&iacute;var'},
  {value:'VND', label:'VND | Vietnamese Don'}
]
export default currencies
